name: CI

on:
  push:
    branches:
      - main
      - develop

env:
  NODE_VERSION: '20.x'
  DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  ARGS: "-az"
  SERVER_PORT: ${{ secrets.SERVER_PORT }}
  USERNAME: ${{ secrets.USERNAME }}
  SERVER_DESTINATION_PROD: ${{ secrets.SERVER_DESTINATION }}
  SERVER_IP_PROD: ${{ secrets.SERVER_IP }}
  SERVER_DESTINATION_DEV: ${{ secrets.SERVER_DESTINATION_STAGING }}
  SERVER_IP_DEV: ${{ secrets.SERVER_IP_STAGING }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Deploy to Production
      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        uses: rustamveer/rsync-deploy@master
        env:
          DEPLOY_KEY: ${{ env.DEPLOY_KEY }}
          ARGS: ${{ env.ARGS }}
          SERVER_PORT: ${{ env.SERVER_PORT }}
          FOLDER: ""
          SERVER_IP: ${{ env.SERVER_IP_PROD }}
          USERNAME: ${{ env.USERNAME }}
          SERVER_DESTINATION: ${{ env.SERVER_DESTINATION_PROD }}

      # Deploy to Develop
      - name: Deploy to Develop
        if: github.ref == 'refs/heads/develop'
        uses: rustamveer/rsync-deploy@master
        env:
          DEPLOY_KEY: ${{ env.DEPLOY_KEY }}
          ARGS: ${{ env.ARGS }}
          SERVER_PORT: ${{ env.SERVER_PORT }}
          FOLDER: ""
          SERVER_IP: ${{ env.SERVER_IP_DEV }}
          USERNAME: ${{ env.USERNAME }}
          SERVER_DESTINATION: ${{ env.SERVER_DESTINATION_DEV }}
